### ISSUE TITLE
Boltgun and other small issues

### ISSUE THREAD

**Issue by Nightmarekiller84** [jekyllgrim/Painslayer#2] opened 2023-10-19 16:28 UTC
1) Electro/Driver:
 the normal Electro/Driver primary fire the Shurikens are traveling at half the distance and then they explode too without hitting anything, this of course without using weapon modifier

2) Boltgun:

my games freezes when I am using this weapon sometimes, I am very sad to say that I never figure it out the conditions of the freezing when using this weapon.

**Comment by jekyllgrim** [comment] 2023-10-19 17:24
1. Not s bug. Shurikens exploding after a bit is intended, it's part of the weapon's mechanic. If you can fire at the right distance, it'll explode near the enemy without hitting them, dealing more damage. Weapon Modifier changes it so that it always explodes on impact.
2. I need more information. GZDoom version, mod version, IWAD being used, other mods/map packs (if any). Also, start GZDoom with `-logfile log.txt +pk_debugmessages 2` startup parameters, play until you encounter a freeze and send me the log.txt.

**Comment by Nightmarekiller84** [comment] 2023-10-19 19:23
1) Oh I see, I read the changelog but I didn't notice that there was such a change

2) gzdoom 4.10.0, Doom2.wad, Painslayer200.pk3
I honestly tried everything but I couldn't produce that log file of yours. I replayed the game 5 times and I can tell for certain that the Bolt-gun can cause freezing, I think is when the weapon modifier is being used. Sorry about that lack of information

On another note the ammo pack chest can be staked and disappear

**Comment by Nightmarekiller84** [comment] 2023-10-19 19:42
after I googled how to create a logfile I manage. here you go:
[error.txt](https://github.com/jekyllgrim/Painslayer/files/13047078/error.txt)

**Comment by jekyllgrim** [comment] 2023-10-20 14:53
The shurikens exploding after some time in flight is not a new mechanic—it's how they worked in the original Painkiller, and it's been like this in the mod since the very first version.

Regarding your Boltgun issue, I'm afraid I've not been able to reproduce it. Best I can suggest for now:

- Download the latest GZDoom ([4.11.1](https://github.com/ZDoom/gzdoom/releases/tag/g4.11.1))
- Download the [dev build of Painslayer](https://github.com/jekyllgrim/Painslayer#how-to-play-the-freshest-dev-build) to play with it.
- Set `pk_debugmessages 3` (not 2, as I asked earlier) in the console when you start playing. (There will be a lot of messages appearing.)
- Keep the log like the last time and see if you can reproduce the freeze.
Maybe I'll be able to figure out something from that, but, unfortunately, no promises.

P.S. If you can record your gameplay and catch the footage of the moment it freezes in addition, that might be helpful too.

**Comment by Nightmarekiller84** [comment] 2023-10-20 16:14
Honestly recording it is gonna be difficult, because the cause of the freezing might be random ? Also I followed everything you have told me but the issue still happens, I can clearly see that even the log file will not help much.

BUT I DID noticed the "requirements" that will cause the freezing. You must have weapon modifier AND Dexterity golden card active at the same time while using the Bolt-Gun. At some point if you are patient and use both fire modes it will eventually happen(it might happen on the very same level or afterwards). Also I think you have to use the weapon modifier NOT AS CARD
I will try to record a video too

**Comment by Nightmarekiller84** [comment] 2023-10-20 17:05
Because there is a size limit, I will give you a link instead
https://we.tl/t-EnSsqkvCos

**Comment by jekyllgrim** [comment] 2023-10-23 12:26
Thank you for describing the conditions. Unfortunately, I'm still not able to reproduce a freeze. I'm afraid that link also doesn't work for me; could you use something like Google Drive, Dropbox, YouTube or Streamable? 

At this point I would suggest trying the mod on a fresh GZDoom install. Specifically, I mean deleting your .ini file and letting GZDoom create a brand-new one on startup (make a backup first because this will remove all custom settings, binds, etc.). See if the bug is reproducible with a fresh ini. Sometimes when the ini file persists over multiple GZDoom versions, it can cause obscure, hard-to-reproduce issues; I've ran into such myself, so that's my recommendation at this stage.

**Comment by Nightmarekiller84** [comment] 2023-10-23 13:49
here is the new link:
https://streamable.com/rymdxi

NOPE IT CAN STILL HAPPEN !!!! , I give up LOL, weapon/modifier(not as card)+dexterity card

anyways I discovered a new issue, the Bolter and Stake gun if by mistake you shoot the Keycards you will not be able to pick them up !!! also they affect some ammo drops too

**Comment by jekyllgrim** [comment] 2023-10-23 15:06
What map is this?

As for the other bug: yes, it's true! It was a huge oversight on my part, and I can't believe it went on for so long. I just pushed a fix for that 0fe40ca8c7000d861d7559119db8e6831c897e21
Thanks for reporting.

**Comment by Nightmarekiller84** [comment] 2023-10-23 15:25
The map is being called 32in24-14.wad but it doesn;t matter really I test the freezing bug in vanilla doom2.wad too so is not a map issue.

Well finally make it worth it for not bothering you for nothing LOL,

**Comment by jekyllgrim** [comment] 2023-10-23 16:05
Does the freeze/slowdown happen if the **Particles intensity** option in Mode Settings is set to Off or Reduced?

UPD: btw, do check that this issue still occurs after the recent fix. It's not impossible that it was related to stakes being able to collide with items. Download the repo (I pushed another quick fix after the previous one) and see if you encounter it again.

**Comment by Nightmarekiller84** [comment] 2023-10-23 17:20
It freezes in Full & Reduced but when is Off it seems to be working fine.

How weird honestly, my game plays fine and smoothly when Particles intensity is Full and yet it freezes because of 1 weapon
And I got to say, it sucks when Particles intensity is Off.
Dang it.

Anyways just in case you are interested or even in mood for it, let me upload my own gzdoom.ini file and try to reproduce the bug. Maybe is some option rather the game itself, who knows ? Otherwise let's leave it be, since no one ever mention it before, is kinda weird too, maybe is just me.

**Comment by Nightmarekiller84** [comment] 2023-10-23 17:28
[gzdoom_portable.zip](https://github.com/jekyllgrim/Painslayer/files/13074320/gzdoom_portable.zip)

**Closed as completed** 2023-12-14 20:51 UTC
